# JVM Properties
java_version=25
org.gradle.jvmargs=-Xmx6G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

## Environment Properties
minecraft_version_range=[26.1,26.2)
neo_version_range=[26,)
loader_version_range=[4,)
interface_injection=false

## Mod Properties
mod_license=MIT
mod_version=0.0.1
mod_group_id=com.qiushui1012.lib
mod_authors=QiuShui1012
